# See configuration comments in “.travis.yml file of KristinitaPelican”:
# https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml
git:
  depth: 1

# Run Travis CI build only  for specific branch:
# https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
branches:
  only:
  - SashaYAML

language: python

python: 3.6

install:
- sudo apt-get install parallel
- pip install -U pip
- bash misc/travis-install.sh
# Move to build directory after HTML Tidy installation:
# https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

before_script:
# [WARNING] If folder “PaletteMiraPackages” no or already exist,
# I get an error “no such file or directory”.
- mkdir PaletteMiraPackages
# [WARNING] Need rename and reverse rename, because traceback in Sublime Text console:
# https://stackoverflow.com/a/13599742/5951529
- mv ruamelprettify.py.palettemira ruamelprettify.py
# ruamel.yaml — remove [brackets], {braces} and 'quotes' from “.yaml” files:
# https://yaml.readthedocs.io/en/latest/
# https://stackoverflow.com/a/49609535/5951529
- python ruamelprettify.py PaletteMira.suricate-profile.yaml PaletteMira.suricate-profile.yaml
# “i18n_yaml_sorter_2” — updated version of outdated package “i18n_yaml_sorter”:
# https://rubygems.org/gems/i18n_yaml_sorter_2
# I don't find another method for YAML sort:
# https://stackoverflow.com/q/49613901/5951529
# Simply in-file sorting doesn't work, need temporary file:
# https://github.com/compwron/i18n_yaml_sorter/#usage
# [NOTE] For chain command in UNIX I need to use “&&”, not “&”:
# https://stackoverflow.com/a/13077311/5951529
- sort_yaml < PaletteMira.suricate-profile.yaml > temp && mv temp PaletteMira.suricate-profile.yaml

script:
# Commit linting for Travis CI:
# http://marionebl.github.io/commitlint/#/guides-ci-setup
- commitlint-travis
# Check EditorConfig
- eclint check
# Travis Client — lint “.travis.yml” file;
# “-x” argument — exit code 1, if any warning.
# https://rubygems.org/gems/travis
- travis lint -x
- flake8 .
- pydocstyle ruamelprettify.py
# yamllint — lint “.yaml” files:
# http://yamllint.readthedocs.io/en/latest/
- yamllint -s PaletteMira.suricate-profile.yaml
# yamljs — convert YAML to JSON:
# https://www.npmjs.com/package/yamljs
# “-p” — prettify indented JSON:
- yaml2json PaletteMira.suricate-profile.yaml > PaletteMira.suricate-profile -p
# “jsonlint-cli” — check JSON:
# https://www.npmjs.com/package/jsonlint-cli
- jsonlint-cli PaletteMira.suricate-profile misc/PaletteMiraPackageDescription.sublime-macro
# The Silver Searcher: fast search in file:
# https://geoff.greer.fm/ag/
# The Platinum Searcher fast also, but re2 library, that use The Platinum Searcher,
# doesn't support lookahead and lookbehind:
# https://github.com/leonid-shevtsov/SearchInProject_SublimeText#installing-search-engines
# https://stackoverflow.com/a/30305934/5951529
# https://github.com/google/re2/issues/156
# “-o” argument — output only finded content, not text before and after them:
- 'ag -o "(?<=# )(.+?)(?= #)" PaletteMira.suricate-profile.yaml > PaletteMiraPackages/active.txt'
- 'ag -o "(?<=# )(.+?)(?= #)" PaletteMiraDeprecated.suricate-profile.yaml > PaletteMiraPackages/deprecated.txt'
# Remove all “.cache” files from the_silver_searcher, that st_package_reviewer don't fail:
# https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks#cache-file-are-redundant-and-created-by-st-automatically
- rm -rf the_silver_searcher/autom4te.cache
# st_package_reviewer — Sublime Text packages checker:
# https://pypi.org/project/st-package-reviewer/
# https://github.com/packagecontrol/st_package_reviewer/wiki
- st_package_reviewer -w .
# XMLStarlet
- xml val misc/PaletteMiraHashesAroundSelectedWords.sane.sublime-snippet

after_success:
# https://www.computerhope.com/issues/ch000798.htm
- rm -rf the_silver_searcher
- mv ruamelprettify.py ruamelprettify.py.palettemira


deploy:
  provider: pages
  on:
    branch: SashaYAML
  keep-history: true
  skip-cleanup: true
  target-branch: SashaDevelop
  repo: Kristinita/SashaScrutinizer
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  project-name: PaletteMira
  verbose: true
