# See configuration comments in “.travis.yml file of KristinitaPelican”:
# https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml
git:
  depth: 1

# Run Travis CI build only  for specific branch:
# https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
branches:
  only:
  - SashaYAML

language: python

python: 3.6

install:
  - pip install -U pip
  - pip install yamllint
  - pip install ruamel.yaml
  - npm install -g yamljs
  - pip install flake8
  - pip install pydocstyle

script:
  - flake8 .
  - pydocstyle
  - yamllint -s PaletteMira.yaml
  - python ruamelprettify.py PaletteMira.yaml PaletteMira.yaml
  - yaml2json PaletteMira.yaml > PaletteMira.suricate-profile

deploy:
  provider: pages
  on:
    branch: SashaYAML
  keep-history: true
  skip-cleanup: true
  target-branch: SashaJSON
  repo: Kristinita/SashaScrutinizer
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  project-name: PaletteMira
  verbose: true
