# See configuration comments in “.travis.yml file of KristinitaPelican”:
# https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml
git:
  depth: 1

# Run Travis CI build only  for specific branch:
# https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
branches:
  only:
  - SashaYAML

language: python

python: 3.6

install:
  - sudo apt-get install parallel
  - pip install -U pip
  - bash travis-install.sh
  - git clone https://github.com/ggreer/the_silver_searcher --depth=1
  - cd the_silver_searcher
  - sudo apt-get install -y automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev
  - bash ./build.sh
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - mkdir PaletteMiraPackages
  - mv ruamelprettify.py.palettemira ruamelprettify.py

script:

  - flake8 .
  - python ruamelprettify.py PaletteMira.yaml PaletteMira.yaml
  - sort_yaml < PaletteMira.yaml > PaletteMira2.yaml && mv PaletteMira2.yaml PaletteMira.yaml
  - yamllint -s PaletteMira.yaml
  # “-p” — prettify indented JSON:
  - yaml2json PaletteMira.yaml > PaletteMira.suricate-profile -p
  - jsonlint -q PaletteMira.suricate-profile
  - 'ag -o "(?<=# )(.+?)(?= #)" PaletteMira.yaml > PaletteMiraPackages/active.txt'
  - 'ag -o "(?<=# )(.+?)(?= #)" PaletteMiraDeprecated.yaml > PaletteMiraPackages/deprecated.txt'
  # Remove all “.cache” files from the_silver_searcher, that st_package_reviewer don't fail:
  # https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks#cache-file-are-redundant-and-created-by-st-automatically
  # https://askubuntu.com/a/377442/582218
  - rm -rf the_silver_searcher/autom4te.cache
  - st_package_reviewer -w .

after_success:
  # https://www.computerhope.com/issues/ch000798.htm
  - rm -rf the_silver_searcher
  - mv ruamelprettify.py ruamelprettify.py.palettemira


deploy:
  provider: pages
  on:
    branch: SashaYAML
  keep-history: true
  skip-cleanup: true
  target-branch: SashaDevelop
  repo: Kristinita/SashaScrutinizer
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  project-name: PaletteMira
  verbose: true
