git:
  depth: 1

# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis CI doesn't support 32-bit platforms:
# https://stackoverflow.com/a/37087813/5951529
language: python

python: 3.6

# Sections:
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# https://stackoverflow.com/a/34384262/5951529

install:
  # [NOTE] Parallelshell works, but no time economy, compare:
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347254717
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347267767
  - pip install -U pip
  - pip install yamllint
  - npm install -g yamljs

script:
  - yamllint -s PaletteMira.yaml
  - yaml2json PaletteMira.yaml > PaletteMira.suricate-profile

# Automatically deploy site to GitHub Pages:
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment/pages/
# Changes not deploy, if pull request:
# https://docs.travis-ci.com/user/deployment#Pull-Requests
# If “script” failed, deploying doesn't run;
# else “pelican_scaffold”, deploy run, even if “script” failed, don't use “pelican_scaffold”:
# https://github.com/textbook/pelican_scaffold
# [WARNING] Custom commit messages doesn't support:
# https://github.com/travis-ci/travis-ci/issues/9287
deploy:
  provider: pages
  on:
    branch: SashaDevelop
  keep-history: true
  # Don't clean output folder:
  # https://docs.travis-ci.com/user/deployment/pages/
  skip-cleanup: true
  target-branch: SashaDevelop
  repo: Kristinita/SashaScrutinizer
  # “GITHUB_API_KEY” is secure variable, that set in repository settings:
  # https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  # https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  github-token: $GITHUB_TOKEN
  # Name and e-mail of committer:
  # https://docs.travis-ci.com/user/deployment/pages/#Further-configuration
  committer-from-gh: true
  # [WARNING] Don't use single quotes in “project-name”:
  # https://github.com/travis-ci/travis-ci/issues/9325
  project-name: PaletteMira
  verbose: true
